Repository phase2/particle, pull requests merged in 2018-09, with the labels that each got.

#355 svg-spritemap-webpack-plugin collides with Bootstrap 4 unless locked to 2.6.0
  package-lock.json
  package.json
Labels: npm, sass

#358 Move the globbing loader to pl specifically.
  apps/drupal/particle.info.yml
  apps/drupal/webpack.drupal.js
  apps/grav/twig-namespaces.yaml
  apps/pl/pattern-lab/config/config.yml
  apps/pl/webpack.pl.js
  config.js
  gulpfile.js
  particle.js
  tools/tasks/gulp-twig-namespaces.js
Labels: pattern lab, webpack

#359 Break out shared particle webpack to its own file for better IDE integration
  .eslintrc.js
  apps/drupal/particle.info.yml
  apps/drupal/webpack.drupal.js
  apps/grav/twig-namespaces.yaml
  apps/grav/webpack.grav.js
  apps/pl/pattern-lab/config/config.yml
  apps/pl/webpack.pl.js
  particle.js
  webpack.particle.js
Labels: webpack

#362 Polyfill fix for also development, browserslist revamp
  .browserslistrc
  package-lock.json
  package.json
  particle.js
Labels: javascript

#367 postcss-preset-env
  package-lock.json
  package.json
  webpack.particle.js
Labels: sass, webpack

#366 Update all npm packages, upgrade jest to 23.
  package-lock.json
  package.json
Labels: testing/linting

#371 PL update deps
  apps/pl/pattern-lab/composer.json
  apps/pl/pattern-lab/composer.lock
Labels: pattern lab

#372 cross-env installed and npm scripts updated.
  package-lock.json
  package.json
Labels: Windows, enhancement

#365 Particle vue fe
  apps/drupal/particle.info.yml
  apps/grav/twig-namespaces.yaml
  apps/pl/pattern-lab/config/config.yml
  package-lock.json
  package.json
  source/_patterns/00-protons/utilities.js
  source/_patterns/02-molecules/example-widget/_vue-facet-table-vue.twig
  source/_patterns/02-molecules/example-widget/_vue-facet-table-vuex.twig
  source/_patterns/02-molecules/example-widget/demo/example-widgets.twig
  source/_patterns/02-molecules/example-widget/demo/index.js
  source/_patterns/02-molecules/example-widget/index.js
  source/_patterns/02-molecules/vue-widget/__tests__/mock-data.json
  source/_patterns/02-molecules/vue-widget/_vue-cards.twig
  source/_patterns/02-molecules/vue-widget/_vue-clock.twig
  source/_patterns/02-molecules/vue-widget/_vue-cryptos.twig
  source/_patterns/02-molecules/vue-widget/_vue-widget.scss
  source/_patterns/02-molecules/vue-widget/_vue-widget.twig
  source/_patterns/02-molecules/vue-widget/_vuex-cryptos.twig
  source/_patterns/02-molecules/vue-widget/demo/index.js
  source/_patterns/02-molecules/vue-widget/demo/vue-html-example.vue
  source/_patterns/02-molecules/vue-widget/demo/vue-widgets.twig
  source/_patterns/02-molecules/vue-widget/index.js
  source/_patterns/02-molecules/vue-widget/src/app.vue
  source/_patterns/02-molecules/vue-widget/src/components/card.vue
  source/_patterns/02-molecules/vue-widget/src/components/widget.vue
  source/_patterns/02-molecules/vue-widget/src/index.js
  source/_patterns/02-molecules/vue-widget/src/vue-cards/app.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/components/banner.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/components/card.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/components/cards.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/index.js
  source/_patterns/02-molecules/vue-widget/src/vue-clock/index.js
  source/_patterns/02-molecules/vue-widget/src/vue-clock/vue-clock.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/components/facet-table-facets.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/components/facet-table-row.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/facet-table.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/index.js
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/components/facet-table-facets.vue
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/components/facet-table-row.vue
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/facet-table.vue
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/index.js
  source/design-system.js
Labels: javascript

#224 example vue component
  .babelrc
  .eslintrc.js
  README.md
  apps/drupal/particle.info.yml
  apps/grav/README.md
  apps/grav/twig-namespaces.yaml
  apps/pl/index.js
  apps/pl/pattern-lab/config/config.yml
  package-lock.json
  package.json
  particle.js
  source/_patterns/00-protons/printing/_forms.scss
  source/_patterns/00-protons/store.js
  source/_patterns/00-protons/utilities.js
  source/_patterns/02-molecules/example-widget/__tests__/example-widget.test.js
  source/_patterns/02-molecules/example-widget/_example-widget.twig
  source/_patterns/02-molecules/example-widget/demo/example-widgets.twig
  source/_patterns/02-molecules/example-widget/demo/index.js
  source/_patterns/02-molecules/example-widget/index.js
  source/_patterns/02-molecules/example-widget/src/action-types.js
  source/_patterns/02-molecules/example-widget/src/actions.js
  source/_patterns/02-molecules/example-widget/src/index.js
  source/_patterns/02-molecules/example-widget/src/reducer.js
  source/_patterns/02-molecules/example-widget/src/store.js
  source/_patterns/02-molecules/example-widget/src/template.js
  source/_patterns/02-molecules/vue-widget/__tests__/mock-data.json
  source/_patterns/02-molecules/vue-widget/_vue-cards.twig
  source/_patterns/02-molecules/vue-widget/_vue-clock.twig
  source/_patterns/02-molecules/vue-widget/_vue-cryptos.twig
  source/_patterns/02-molecules/vue-widget/_vue-widget.scss
  source/_patterns/02-molecules/vue-widget/_vuex-cryptos.twig
  source/_patterns/02-molecules/vue-widget/demo/index.js
  source/_patterns/02-molecules/vue-widget/demo/vue-html-example.vue
  source/_patterns/02-molecules/vue-widget/demo/vue-widgets.twig
  source/_patterns/02-molecules/vue-widget/index.js
  source/_patterns/02-molecules/vue-widget/src/vue-cards/app.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/components/banner.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/components/card.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/components/cards.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cards/index.js
  source/_patterns/02-molecules/vue-widget/src/vue-clock/index.js
  source/_patterns/02-molecules/vue-widget/src/vue-clock/vue-clock.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/components/facet-table-facets.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/components/facet-table-row.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/facet-table.vue
  source/_patterns/02-molecules/vue-widget/src/vue-cryptos/index.js
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/components/facet-table-facets.vue
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/components/facet-table-row.vue
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/facet-table.vue
  source/_patterns/02-molecules/vue-widget/src/vuex-cryptos/index.js
  source/design-system.js
  webpack.particle.js
Labels: javascript

#386 All patterns start with a best practice of checking for element to exist before further logic
  .prettierignore
  tools/new-component/templates/pattern.js
Labels: javascript

#388 Full source map for production.
  webpack.particle.js
Labels: webpack

#384 require.context() for "globbing"
  README.md
  source/_patterns/02-molecules/vue-widget/index.js
  source/design-system.js
Labels: webpack

#391 settings override example
  apps/drupal/index.js
  source/_patterns/01-atoms/alert/index.js
  source/_patterns/01-atoms/button/index.js
  source/_patterns/01-atoms/dropdown/index.js
  source/_patterns/01-atoms/list-group/index.js
  source/_patterns/02-molecules/carousel/index.js
  source/_patterns/03-organisms/accordion/index.js
  source/_patterns/03-organisms/navbar/index.js
  tools/new-component/templates/pattern.js
Labels: javascript

#392 Update all pl composer.json deps.
  apps/pl/pattern-lab/composer.json
  apps/pl/pattern-lab/composer.lock
Labels: PHP, pattern lab

#393 Update npm deps, make new components more obvious.
  package-lock.json
  package.json
  tools/new-component/templates/_pattern.twig
Labels: npm

#395 Minimum composer.json to get picked up by composer, twig linting
  apps/pl/pattern-lab/composer.json
  apps/pl/pattern-lab/composer.lock
  composer.json
  package.json
Labels: PHP
