Repository phase2/particle, pull requests merged in 2018-06, with the labels that each got.

#302 Relative pathing url added to demonstration bg images.
  package-lock.json
  package.json
  source/_patterns/01-atoms/image/demo/_image-demo.scss
  source/_patterns/01-atoms/image/demo/image-bg.twig
  source/_patterns/01-atoms/image/demo/image-styles.twig
  source/_patterns/01-atoms/image/demo/index.js
  webpack.particle.dev.js
  webpack.particle.prod.js
Labels: sass, webpack

#312 Particle #310 Rip out Lodash
  apps/drupal/drupal-lodash.js
  apps/drupal/particle.info.yml
  apps/drupal/particle.libraries.yml
  apps/drupal/webpack.drupal.shared.js
  package-lock.json
Labels: drupal, javascript

#320 Migrate lodash to devdependencies
  apps/pl/index.js
  package-lock.json
  package.json
  tools/new-component/index.js
  tools/tasks/gulp-twig-namespaces.js
Labels: node

#244 Initial take on adding prettier formatting tool.
  .eslintrc.js
  .huskyrc
  .prettierignore
  .prettierrc.js
  .stylelintignore
  .stylelintrc
  .yo-rc.json
  apps/drupal/webpack.drupal.dev.js
  apps/drupal/webpack.drupal.shared.js
  apps/grav/webpack.grav.dev.js
  apps/grav/webpack.grav.prod.js
  apps/grav/webpack.grav.shared.js
  apps/pl/index.js
  apps/pl/scss/_scss2json.scss
  apps/pl/scss/_styleguide.scss
  apps/pl/webpack.pl.dev.js
  apps/pl/webpack.pl.shared.js
  gulpfile.js
  jest.config.js
  package-lock.json
  package.json
  source/_data/scssVariables.json
  source/_patterns/00-protons/_variables.scss
  source/_patterns/00-protons/non-printing/_mixins.scss
  source/_patterns/00-protons/printing/_html-elements.scss
  source/_patterns/01-atoms/badge/_badge.scss
  source/_patterns/01-atoms/branding/_branding.scss
  source/_patterns/01-atoms/button/_button.scss
  source/_patterns/01-atoms/dropdown/_dropdown.scss
  source/_patterns/01-atoms/icon/scss/_icon-mixins.scss
  source/_patterns/01-atoms/icon/scss/_icon.scss
  source/_patterns/01-atoms/icon/templates/iconfont-template.js
  source/_patterns/01-atoms/list-group/_list-group.scss
  source/_patterns/02-molecules/example-widget/__tests__/example-widget.test.js
  source/_patterns/02-molecules/example-widget/__tests__/mock-data.json
  source/_patterns/02-molecules/example-widget/_example-widget.scss
  source/_patterns/02-molecules/example-widget/src/actions.js
  source/_patterns/02-molecules/example-widget/src/reducer.js
  source/_patterns/02-molecules/example-widget/src/store.js
  source/_patterns/02-molecules/example-widget/src/template.js
  source/_patterns/02-molecules/nav/_nav.scss
  source/_patterns/02-molecules/pagination/_pagination.scss
  source/_patterns/03-organisms/footer/_footer.scss
  source/_patterns/03-organisms/navbar/_navbar.scss
  source/_patterns/04-templates/basic-page/_basic-page.scss
  source/_patterns/05-pages/demo/index.js
  source/design-system.js
  tools/new-component/index.js
  tools/new-component/templates/_pattern.scss
  tools/tasks/gulp-twig-namespaces.js
  tools/tasks/pl-compile.js
  tools/tests/accessibility/pa11y.js
  tools/webpack/run-script-after-emit.js
  tools/webpack/run-script-on-filetype-change.js
  webpack.particle.dev.js
  webpack.particle.prod.js
Labels: testing/linting

#329 Remove regenerator-runtime dep as it is not referenced.
  package.json
Labels: npm

#330 Add root:true to eslintrc
  .eslintrc.js
Labels: testing/linting

#331 Add drupal and grav to ci test build
  package.json
Labels: testing/linting
